-- ═══════════════════════════════════════════════════════════════════
-- Payment Proof — Add proof of payment support to fee records
-- ═══════════════════════════════════════════════════════════════════
--
-- Adds a payment_proof_url column to fee_records and storage policies
-- for the payment-proofs bucket. Bucket must be created manually in
-- Supabase dashboard as a PRIVATE bucket (3 MB limit).
-- ═══════════════════════════════════════════════════════════════════

BEGIN;

-- New column for proof of payment URL
ALTER TABLE fee_records ADD COLUMN IF NOT EXISTS payment_proof_url TEXT;

-- Storage policies for payment-proofs bucket (authenticated only — admins upload/manage)
-- Bucket is PRIVATE — proofs are accessed via signed URLs generated by the backend
-- Parents view via GET /api/portal/fees/:id/proof-url (returns a 1-hour signed URL)
DROP POLICY IF EXISTS "Auth users can upload payment proofs" ON storage.objects;
CREATE POLICY "Auth users can upload payment proofs"
  ON storage.objects FOR INSERT
  TO authenticated
  WITH CHECK (bucket_id = 'payment-proofs');

DROP POLICY IF EXISTS "Auth users can read payment proofs" ON storage.objects;
CREATE POLICY "Auth users can read payment proofs"
  ON storage.objects FOR SELECT
  TO authenticated
  USING (bucket_id = 'payment-proofs');

DROP POLICY IF EXISTS "Auth users can update payment proofs" ON storage.objects;
CREATE POLICY "Auth users can update payment proofs"
  ON storage.objects FOR UPDATE
  TO authenticated
  USING (bucket_id = 'payment-proofs');

DROP POLICY IF EXISTS "Auth users can delete payment proofs" ON storage.objects;
CREATE POLICY "Auth users can delete payment proofs"
  ON storage.objects FOR DELETE
  TO authenticated
  USING (bucket_id = 'payment-proofs');

COMMIT;
